name: CI-CD

on:
  push:
    branches: [ master ]

jobs:
  # JobName
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          apt-get update > /dev/null
          apt-get install git wget unzip zip python3 -y > /dev/null
          curl --silent "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" > /dev/null
          python3 get-pip.py > /dev/null
          pip install awscli --upgrade > /dev/null
          aws configure set region us-east-2 > /dev/null
          aws
          cd $GITHUB_WORKSPACE
          ls
          echo Add other actions to build,
          echo test, and deploy your project.
          echo line 3
